# Generated by Django 4.2.4 on 2024-01-30 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_aes', models.CharField(blank=True, max_length=1000)),
                ('receiver_aes', models.CharField(blank=True, max_length=1000)),
                ('time_shared', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steganography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('message_size', models.IntegerField(default=0)),
                ('compressed_message_size', models.IntegerField(default=0)),
                ('compression_time', models.FloatField(default=0)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steganography_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='steganography_sender', to=settings.AUTH_USER_MODEL)),
                ('shared_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steganography_encryption_key', to='Messaging.sharedkey')),
            ],
        ),
    ]
